// app/api/hellocoop/route.js
// generated by @hellocoop/quickstart --nextjs on 2026-05-27T11:01:21.094Z
// NOTE: this file should not need to be edited
import config from '../../../hello.config'
import { appAuth } from '@hellocoop/nextjs'
export const { GET } = appAuth(config)
